### ISSUE TITLE
Testimonial Title Spacing Issue

### ISSUE THREAD

**Issue by amirhossain93** [themesgrove/widgetkit#13]
Testimonial Element:
--------------------
 1. Layout -> Screen 1: Title spacing should be bottom but spacing working both top and bottom https://prnt.sc/vh9i8o
Also there isn't any option for image spacing

**Comment by anamwp** [comment]
fixed. Need to release with 2.3.7.4

**Comment by anamwp** [comment]
Released with 2.3.7.4
